Import All the libraries

In [273]:
import torch as torch
import torch.nn as nn
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import OneHotEncoder

laod the dataset CSV File

In [274]:
df = pd.read_csv("data/Housing.csv")

for reproducibility

In [275]:
torch.manual_seed(42)

np.random.seed(42)

In [276]:
df.head(10)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
6,10150000,8580,4,3,4,yes,no,no,no,yes,2,yes,semi-furnished
7,10150000,16200,5,3,2,yes,no,no,no,no,0,no,unfurnished
8,9870000,8100,4,1,2,yes,yes,yes,no,yes,2,yes,furnished
9,9800000,5750,3,2,4,yes,yes,no,no,yes,1,yes,unfurnished

In [277]:
# the missing values are removed directly within the original DataFrame
df.dropna(inplace=True)

In [278]:
df.head(10)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
6,10150000,8580,4,3,4,yes,no,no,no,yes,2,yes,semi-furnished
7,10150000,16200,5,3,2,yes,no,no,no,no,0,no,unfurnished
8,9870000,8100,4,1,2,yes,yes,yes,no,yes,2,yes,furnished
9,9800000,5750,3,2,4,yes,yes,no,no,yes,1,yes,unfurnished

In [279]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    str
 6   guestroom         545 non-null    str
 7   basement          545 non-null    str
 8   hotwaterheating   545 non-null    str
 9   airconditioning   545 non-null    str
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    str
 12  furnishingstatus  545 non-null    str
dtypes: int64(6), str(7)
memory usage: 55.5 KB

techniques used to convert categorical (text) data into numerical values for machine learning

In [280]:
label_encoder = LabelEncoder()

In [306]:
df['mainroad'] = label_encoder.fit_transform(df['mainroad'])
df['guestroom'] = label_encoder.fit_transform(df['guestroom'])
df['basement'] = label_encoder.fit_transform(df['basement'])
df['airconditioning'] = label_encoder.fit_transform(df['airconditioning'])
df['prefarea'] = label_encoder.fit_transform(df['prefarea'])
df['furnishingstatus'] = label_encoder.fit_transform(df['furnishingstatus'])
df['hotwaterheating'] = label_encoder.fit_transform(df['hotwaterheating'])

In [ ]:
pd.get_dummies(data=df, columns=['furnishingstatus'], drop_first=True)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_1,furnishingstatus_2
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,False,False
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,False,False
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,True,False
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,False,False
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,2,0,False,True
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,True,False
542,1750000,3620,2,1,1,1,0,0,0,0,0,0,False,True
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,False,False
544,1750000,3850,3,1,2,1,0,0,0,0,0,0,False,True

In [283]:
df.head(10)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    int64
 6   guestroom         545 non-null    int64
 7   basement          545 non-null    int64
 8   hotwaterheating   545 non-null    int64
 9   airconditioning   545 non-null    int64
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    int64
 12  furnishingstatus  545 non-null    int64
dtypes: int64(13)
memory usage: 55.5 KB

In [284]:
X_raw = df.drop('price', axis=1)
y_raw = df['price']

In [285]:
X_raw

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,7420,4,2,3,1,0,0,0,1,2,1,0
1,8960,4,4,4,1,0,0,0,1,3,0,0
2,9960,3,2,2,1,0,1,0,0,2,1,1
3,7500,4,2,2,1,0,1,0,1,3,1,0
4,7420,4,1,2,1,1,1,0,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
540,3000,2,1,1,1,0,1,0,0,2,0,2
541,2400,3,1,1,0,0,0,0,0,0,0,1
542,3620,2,1,1,1,0,0,0,0,0,0,2
543,2910,3,1,1,0,0,0,0,0,0,0,0
544,3850,3,1,2,1,0,0,0,0,0,0,2

In [286]:
y_raw

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64

In [287]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X_raw)

In [309]:
target_scaler = StandardScaler()

Y_scaled = target_scaler.fit_transform(y_raw.values.reshape(-1, 1))

In [289]:
X_scaled

array([[ 1.04672629,  1.40341936,  1.42181174, ...,  1.51769249,
         1.80494113, -1.40628573],
       [ 1.75700953,  1.40341936,  5.40580863, ...,  2.67940935,
        -0.55403469, -1.40628573],
       [ 2.21823241,  0.04727831,  1.42181174, ...,  1.51769249,
         1.80494113, -0.09166185],
       ...,
       [-0.70592066, -1.30886273, -0.57018671, ..., -0.80574124,
        -0.55403469,  1.22296203],
       [-1.03338891,  0.04727831, -0.57018671, ..., -0.80574124,
        -0.55403469, -1.40628573],
       [-0.5998394 ,  0.04727831, -0.57018671, ..., -0.80574124,
        -0.55403469,  1.22296203]], shape=(545, 12))

In [310]:
Y_scaled

array([[ 4.56636513e+00],
       [ 4.00448405e+00],
       [ 4.00448405e+00],
       [ 3.98575468e+00],
       [ 3.55497918e+00],
       [ 3.25530927e+00],
       [ 2.88072189e+00],
       [ 2.88072189e+00],
       [ 2.73088693e+00],
       [ 2.69342819e+00],
       [ 2.69342819e+00],
       [ 2.62974834e+00],
       [ 2.43121702e+00],
       [ 2.39375829e+00],
       [ 2.39375829e+00],
       [ 2.31884081e+00],
       [ 2.31884081e+00],
       [ 2.24392333e+00],
       [ 2.20646459e+00],
       [ 2.18773522e+00],
       [ 2.13154711e+00],
       [ 2.09408838e+00],
       [ 2.07535901e+00],
       [ 2.07535901e+00],
       [ 2.03790027e+00],
       [ 2.01917090e+00],
       [ 1.97796629e+00],
       [ 1.94425342e+00],
       [ 1.94425342e+00],
       [ 1.94425342e+00],
       [ 1.94425342e+00],
       [ 1.94425342e+00],
       [ 1.88806531e+00],
       [ 1.83187721e+00],
       [ 1.79441847e+00],
       [ 1.77351649e+00],
       [ 1.75321385e+00],
       [ 1.71950099e+00],
       [ 1.71013630e+00],
       [ 1.68204225e+00],
       [ 1.66331288e+00],
       [ 1.64458351e+00],
       [ 1.56966604e+00],
       [ 1.56966604e+00],
       [ 1.49474856e+00],
       [ 1.49474856e+00],
       [ 1.47601919e+00],
       [ 1.45728982e+00],
       [ 1.43856045e+00],
       [ 1.41983108e+00],
       [ 1.41983108e+00],
       [ 1.41983108e+00],
       [ 1.38237234e+00],
       [ 1.38237234e+00],
       [ 1.38237234e+00],
       [ 1.38237234e+00],
       [ 1.37862647e+00],
       [ 1.32618423e+00],
       [ 1.30745486e+00],
       [ 1.30745486e+00],
       [ 1.26999613e+00],
       [ 1.23253739e+00],
       [ 1.23253739e+00],
       [ 1.21380802e+00],
       [ 1.19507865e+00],
       [ 1.15761991e+00],
       [ 1.15761991e+00],
       [ 1.13889054e+00],
       [ 1.12016117e+00],
       [ 1.08270243e+00],
       [ 1.08270243e+00],
       [ 1.06397306e+00],
       [ 1.04524369e+00],
       [ 1.02651432e+00],
       [ 1.00778496e+00],
       [ 1.00778496e+00],
       [ 1.00778496e+00],
       [ 1.00778496e+00],
       [ 1.00778496e+00],
       [ 1.00778496e+00],
       [ 9.96547334e-01],
       [ 9.89055586e-01],
       [ 9.89055586e-01],
       [ 9.70326217e-01],
       [ 9.32867478e-01],
       [ 9.32867478e-01],
       [ 9.32867478e-01],
       [ 9.14138109e-01],
       [ 9.14138109e-01],
       [ 8.95408740e-01],
       [ 8.95408740e-01],
       [ 8.84171118e-01],
       [ 8.76679370e-01],
       [ 8.20491262e-01],
       [ 8.20491262e-01],
       [ 8.20491262e-01],
       [ 8.20491262e-01],
       [ 8.20491262e-01],
       [ 8.16745389e-01],
       [ 8.01761893e-01],
       [ 7.83032524e-01],
       [ 7.83032524e-01],
       [ 7.64303154e-01],
       [ 7.64303154e-01],
       [ 7.64303154e-01],
       [ 7.45573785e-01],
       [ 7.45573785e-01],
       [ 7.26844416e-01],
       [ 7.17479731e-01],
       [ 7.08115046e-01],
       [ 7.08115046e-01],
       [ 7.08115046e-01],
       [ 7.04369173e-01],
       [ 7.04369173e-01],
       [ 6.70656308e-01],
       [ 6.70656308e-01],
       [ 6.70656308e-01],
       [ 6.33197569e-01],
       [ 6.33197569e-01],
       [ 6.33197569e-01],
       [ 6.33197569e-01],
       [ 6.33197569e-01],
       [ 6.33197569e-01],
       [ 6.33197569e-01],
       [ 6.33197569e-01],
       [ 6.29451695e-01],
       [ 5.95738831e-01],
       [ 5.95738831e-01],
       [ 5.91992957e-01],
       [ 5.91992957e-01],
       [ 5.88247083e-01],
       [ 5.58280092e-01],
       [ 5.58280092e-01],
       [ 5.58280092e-01],
       [ 5.54534218e-01],
       [ 5.39550723e-01],
       [ 5.20821353e-01],
       [ 5.20821353e-01],
       [ 5.20821353e-01],
       [ 5.20821353e-01],
       [ 5.20821353e-01],
       [ 4.73997930e-01],
       [ 4.45903876e-01],
       [ 4.45903876e-01],
       [ 4.45903876e-01],
       [ 4.45903876e-01],
       [ 4.45903876e-01],
       [ 4.45903876e-01],
       [ 4.45903876e-01],
       [ 4.45903876e-01],
       [ 4.45903876e-01],
       [ 4.27174507e-01],
       [ 4.27174507e-01],
       [ 4.08445137e-01],
       [ 4.08445137e-01],
       [ 4.08445137e-01],
       [ 4.04699264e-01],
       [ 3.89715768e-01],
       [ 3.89715768e-01],
       [ 3.70986399e-01],
       [ 3.70986399e-01],
       [ 3.70986399e-01],
       [ 3.70986399e-01],
       [ 3.52257029e-01],
       [ 3.33527660e-01],
       [ 3.29781786e-01],
       [ 2.96068921e-01],
       [ 2.77339552e-01],
       [ 2.58610183e-01],
       [ 2.58610183e-01],
       [ 2.58610183e-01],
       [ 2.58610183e-01],
       [ 2.58610183e-01],
       [ 2.58610183e-01],
       [ 2.58610183e-01],
       [ 2.58610183e-01],
       [ 2.58610183e-01],
       [ 2.54864309e-01],
       [ 2.47372561e-01],
       [ 2.39880814e-01],
       [ 2.39880814e-01],
       [ 2.39880814e-01],
       [ 2.02422075e-01],
       [ 2.02422075e-01],
       [ 1.83692706e-01],
       [ 1.83692706e-01],
       [ 1.83692706e-01],
       [ 1.83692706e-01],
       [ 1.64963336e-01],
       [ 1.46233967e-01],
       [ 1.46233967e-01],
       [ 1.46233967e-01],
       [ 1.46233967e-01],
       [ 1.42488093e-01],
       [ 1.27504598e-01],
       [ 1.08775228e-01],
       [ 1.08775228e-01],
       [ 1.01283481e-01],
       [ 9.00458590e-02],
       [ 7.50623635e-02],
       [ 7.13164897e-02],
       [ 7.13164897e-02],
       [ 7.13164897e-02],
       [ 7.13164897e-02],
       [ 7.13164897e-02],
       [ 7.13164897e-02],
       [ 7.13164897e-02],
       [ 7.13164897e-02],
       [ 7.13164897e-02],
       [ 7.13164897e-02],
       [ 7.13164897e-02],
       [ 7.13164897e-02],
       [ 6.75706158e-02],
       [ 6.75706158e-02],
       [ 5.25871204e-02],
       [ 3.38577510e-02],
       [ 3.38577510e-02],
       [ 3.38577510e-02],
       [ 3.38577510e-02],
       [ 1.51283817e-02],
       [ 1.51283817e-02],
       [ 1.44886277e-04],
       [-3.60098759e-03],
       [-3.60098759e-03],
       [-3.60098759e-03],
       [-7.34686145e-03],
       [-4.10597262e-02],
       [-4.10597262e-02],
       [-4.10597262e-02],
       [-4.10597262e-02],
       [-4.10597262e-02],
       [-4.10597262e-02],
       [-5.97890955e-02],
       [-7.85184649e-02],
       [-7.85184649e-02],
       [-7.85184649e-02],
       [-7.85184649e-02],
       [-7.85184649e-02],
       [-8.22643387e-02],
       [-9.72478342e-02],
       [-9.72478342e-02],
       [-1.15977203e-01],
       [-1.15977203e-01],
       [-1.15977203e-01],
       [-1.15977203e-01],
       [-1.15977203e-01],
       [-1.15977203e-01],
       [-1.15977203e-01],
       [-1.19723077e-01],
       [-1.19723077e-01],
       [-1.34706573e-01],
       [-1.34706573e-01],
       [-1.34706573e-01],
       [-1.34706573e-01],
       [-1.53435942e-01],
       [-1.53435942e-01],
       [-1.53435942e-01],
       [-1.53435942e-01],
       [-1.53435942e-01],
       [-1.57181816e-01],
       [-1.57181816e-01],
       [-1.57181816e-01],
       [-1.72165311e-01],
       [-1.90894681e-01],
       [-1.90894681e-01],
       [-1.94640555e-01],
       [-1.94640555e-01],
       [-1.94640555e-01],
       [-2.05878176e-01],
       [-2.09624050e-01],
       [-2.28353419e-01],
       [-2.28353419e-01],
       [-2.28353419e-01],
       [-2.28353419e-01],
       [-2.28353419e-01],
       [-2.39591041e-01],
       [-2.47082789e-01],
       [-2.47082789e-01],
       [-2.62066284e-01],
       [-2.65812158e-01],
       [-2.65812158e-01],
       [-2.65812158e-01],
       [-2.65812158e-01],
       [-2.65812158e-01],
       [-2.65812158e-01],
       [-2.84541527e-01],
       [-2.84541527e-01],
       [-3.03270897e-01],
       [-3.03270897e-01],
       [-3.03270897e-01],
       [-3.03270897e-01],
       [-3.03270897e-01],
       [-3.03270897e-01],
       [-3.03270897e-01],
       [-3.03270897e-01],
       [-3.03270897e-01],
       [-3.03270897e-01],
       [-3.03270897e-01],
       [-3.03270897e-01],
       [-3.03270897e-01],
       [-3.03270897e-01],
       [-3.03270897e-01],
       [-3.03270897e-01],
       [-3.03270897e-01],
       [-3.07016771e-01],
       [-3.07016771e-01],
       [-3.22000266e-01],
       [-3.22000266e-01],
       [-3.22000266e-01],
       [-3.40729635e-01],
       [-3.40729635e-01],
       [-3.44475509e-01],
       [-3.57586068e-01],
       [-3.59459005e-01],
       [-3.59459005e-01],
       [-3.59459005e-01],
       [-3.78188374e-01],
       [-3.78188374e-01],
       [-3.78188374e-01],
       [-3.78188374e-01],
       [-3.78188374e-01],
       [-3.96917743e-01],
       [-3.96917743e-01],
       [-3.96917743e-01],
       [-4.06282428e-01],
       [-4.06282428e-01],
       [-4.15647113e-01],
       [-4.15647113e-01],
       [-4.15647113e-01],
       [-4.15647113e-01],
       [-4.15647113e-01],
       [-4.53105851e-01],
       [-4.53105851e-01],
       [-4.53105851e-01],
       [-4.53105851e-01],
       [-4.53105851e-01],
       [-4.53105851e-01],
       [-4.53105851e-01],
       [-4.71835221e-01],
       [-4.71835221e-01],
       [-4.90564590e-01],
       [-4.90564590e-01],
       [-4.90564590e-01],
       [-4.90564590e-01],
       [-4.90564590e-01],
       [-4.90564590e-01],
       [-4.90564590e-01],
       [-4.98056338e-01],
       [-5.09293959e-01],
       [-5.28023328e-01],
       [-5.28023328e-01],
       [-5.28023328e-01],
       [-5.28023328e-01],
       [-5.28023328e-01],
       [-5.28023328e-01],
       [-5.31769202e-01],
       [-5.31769202e-01],
       [-5.31769202e-01],
       [-5.46752698e-01],
       [-5.65482067e-01],
       [-5.65482067e-01],
       [-5.65482067e-01],
       [-5.65482067e-01],
       [-5.65482067e-01],
       [-5.69227941e-01],
       [-5.69227941e-01],
       [-5.84211436e-01],
       [-5.84211436e-01],
       [-5.84211436e-01],
       [-5.84211436e-01],
       [-6.02940806e-01],
       [-6.02940806e-01],
       [-6.02940806e-01],
       [-6.02940806e-01],
       [-6.02940806e-01],
       [-6.02940806e-01],
       [-6.02940806e-01],
       [-6.02940806e-01],
       [-6.02940806e-01],
       [-6.06686680e-01],
       [-6.21670175e-01],
       [-6.21670175e-01],
       [-6.40399544e-01],
       [-6.40399544e-01],
       [-6.40399544e-01],
       [-6.40399544e-01],
       [-6.59128914e-01],
       [-6.77858283e-01],
       [-6.77858283e-01],
       [-6.77858283e-01],
       [-6.77858283e-01],
       [-6.77858283e-01],
       [-6.77858283e-01],
       [-6.77858283e-01],
       [-6.77858283e-01],
       [-6.77858283e-01],
       [-6.77858283e-01],
       [-6.77858283e-01],
       [-6.77858283e-01],
       [-6.77858283e-01],
       [-6.77858283e-01],
       [-6.77858283e-01],
       [-6.77858283e-01],
       [-6.77858283e-01],
       [-6.81604157e-01],
       [-6.96587652e-01],
       [-6.96587652e-01],
       [-6.96587652e-01],
       [-7.15317022e-01],
       [-7.15317022e-01],
       [-7.15317022e-01],
       [-7.15317022e-01],
       [-7.15317022e-01],
       [-7.15317022e-01],
       [-7.19062896e-01],
       [-7.34046391e-01],
       [-7.34046391e-01],
       [-7.34046391e-01],
       [-7.52775760e-01],
       [-7.52775760e-01],
       [-7.52775760e-01],
       [-7.52775760e-01],
       [-7.52775760e-01],
       [-7.52775760e-01],
       [-7.52775760e-01],
       [-7.52775760e-01],
       [-7.56521634e-01],
       [-7.67759256e-01],
       [-7.71505130e-01],
       [-7.71505130e-01],
       [-7.90234499e-01],
       [-7.90234499e-01],
       [-7.90234499e-01],
       [-7.90234499e-01],
       [-7.90234499e-01],
       [-7.90234499e-01],
       [-7.90234499e-01],
       [-7.90234499e-01],
       [-8.08963868e-01],
       [-8.08963868e-01],
       [-8.20201490e-01],
       [-8.27693238e-01],
       [-8.27693238e-01],
       [-8.27693238e-01],
       [-8.27693238e-01],
       [-8.65151976e-01],
       [-8.65151976e-01],
       [-8.65151976e-01],
       [-8.65151976e-01],
       [-8.65151976e-01],
       [-8.65151976e-01],
       [-8.65151976e-01],
       [-8.65151976e-01],
       [-8.65151976e-01],
       [-8.68897850e-01],
       [-8.76389598e-01],
       [-8.81821115e-01],
       [-8.83881346e-01],
       [-8.83881346e-01],
       [-8.83881346e-01],
       [-8.98864841e-01],
       [-9.02610715e-01],
       [-9.02610715e-01],
       [-9.02610715e-01],
       [-9.02610715e-01],
       [-9.21340084e-01],
       [-9.40069453e-01],
       [-9.40069453e-01],
       [-9.40069453e-01],
       [-9.40069453e-01],
       [-9.40069453e-01],
       [-9.40069453e-01],
       [-9.40069453e-01],
       [-9.43815327e-01],
       [-9.58798823e-01],
       [-9.66290571e-01],
       [-9.77528192e-01],
       [-9.77528192e-01],
       [-9.77528192e-01],
       [-9.77528192e-01],
       [-9.77528192e-01],
       [-9.77528192e-01],
       [-9.77528192e-01],
       [-9.77528192e-01],
       [-1.01498693e+00],
       [-1.01498693e+00],
       [-1.01498693e+00],
       [-1.01498693e+00],
       [-1.02435162e+00],
       [-1.03371630e+00],
       [-1.03371630e+00],
       [-1.03371630e+00],
       [-1.05244567e+00],
       [-1.05244567e+00],
       [-1.08990441e+00],
       [-1.08990441e+00],
       [-1.10863378e+00],
       [-1.12736315e+00],
       [-1.12736315e+00],
       [-1.12736315e+00],
       [-1.12736315e+00],
       [-1.12736315e+00],
       [-1.12736315e+00],
       [-1.12736315e+00],
       [-1.13110902e+00],
       [-1.13110902e+00],
       [-1.15733014e+00],
       [-1.16482189e+00],
       [-1.16482189e+00],
       [-1.16482189e+00],
       [-1.20228062e+00],
       [-1.20228062e+00],
       [-1.20228062e+00],
       [-1.22100999e+00],
       [-1.22100999e+00],
       [-1.23973936e+00],
       [-1.23973936e+00],
       [-1.23973936e+00],
       [-1.23973936e+00],
       [-1.23973936e+00],
       [-1.23973936e+00],
       [-1.26221461e+00],
       [-1.27719810e+00],
       [-1.27719810e+00],
       [-1.27719810e+00],
       [-1.29592747e+00],
       [-1.31465684e+00],
       [-1.33338621e+00],
       [-1.33338621e+00],
       [-1.33338621e+00],
       [-1.35211558e+00],
       [-1.35586145e+00],
       [-1.40830369e+00],
       [-1.42703306e+00],
       [-1.42703306e+00],
       [-1.42703306e+00],
       [-1.50195053e+00],
       [-1.53940927e+00],
       [-1.53940927e+00],
       [-1.55813864e+00],
       [-1.57686801e+00],
       [-1.60514936e+00],
       [-1.61432675e+00],
       [-1.61432675e+00],
       [-1.61432675e+00]])

In [291]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, Y_scaled, test_size=0.2, random_state=42)

In [292]:
class HousingDataset(Dataset):
    def __init__(self, features, targets):
        self.X = torch.tensor(features, dtype=torch.float32)
        self.y = torch.tensor(targets, dtype=torch.float32).view(-1, 1)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

In [293]:
train_housing_dataset = HousingDataset(X_train, y_train)

test_housing_dataset = HousingDataset(X_test, y_test)

In [294]:
train_loader = DataLoader(train_housing_dataset, batch_size=32, shuffle=True)

for batch_X, batch_y in train_loader:
    print("Batch X Shape:", batch_X.shape)
    print("Batch y Shape:", batch_y.shape)
    break

Batch X Shape: torch.Size([32, 12])
Batch y Shape: torch.Size([32, 1])

In [295]:
test_loader = DataLoader(test_housing_dataset, batch_size=32, shuffle=False)

In [311]:
class HousePricePredictor(nn.Module):
    def __init__(self, input_dim):
        super(HousePricePredictor, self).__init__()
        self.fc1 = nn.Linear(input_dim, 64)
        self.fc2 = nn.Linear(64, 32)
        self.fc3 = nn.Linear(32, 1)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.fc3(x)
        return x

In [297]:
model = HousePricePredictor(input_dim=X_scaled.shape[1])

In [298]:
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

In [299]:
epochs = 50

for epoch in range(epochs):

    epoch_loss = 0

    for batch_X, batch_y in train_loader:

        predictions = model(batch_X)

        loss = criterion(predictions, batch_y)

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()

        epoch_loss += loss.item() * batch_X.size(0)

    epoch_loss /= len(train_loader.dataset)

    print(f"Epoch [{epoch+1}/{epochs}], Loss: {epoch_loss:.4f}")

Epoch [1/50], Loss: 0.4723
Epoch [2/50], Loss: 0.3000
Epoch [3/50], Loss: 0.2388
Epoch [4/50], Loss: 0.2176
Epoch [5/50], Loss: 0.1992
Epoch [6/50], Loss: 0.1834
Epoch [7/50], Loss: 0.1638
Epoch [8/50], Loss: 0.1553
Epoch [9/50], Loss: 0.1571
Epoch [10/50], Loss: 0.1608
Epoch [11/50], Loss: 0.1427
Epoch [12/50], Loss: 0.1279
Epoch [13/50], Loss: 0.1237
Epoch [14/50], Loss: 0.1218
Epoch [15/50], Loss: 0.1125
Epoch [16/50], Loss: 0.1156
Epoch [17/50], Loss: 0.1223
Epoch [18/50], Loss: 0.1499
Epoch [19/50], Loss: 0.1209
Epoch [20/50], Loss: 0.1228
Epoch [21/50], Loss: 0.1100
Epoch [22/50], Loss: 0.1036
Epoch [23/50], Loss: 0.0889
Epoch [24/50], Loss: 0.0755
Epoch [25/50], Loss: 0.0717
Epoch [26/50], Loss: 0.0668
Epoch [27/50], Loss: 0.0699
Epoch [28/50], Loss: 0.0781
Epoch [29/50], Loss: 0.0815
Epoch [30/50], Loss: 0.0829
Epoch [31/50], Loss: 0.0877
Epoch [32/50], Loss: 0.0682
Epoch [33/50], Loss: 0.0655
Epoch [34/50], Loss: 0.0619
Epoch [35/50], Loss: 0.0758
Epoch [36/50], Loss: 0.0776
Epoch [37/50], Loss: 0.0688
Epoch [38/50], Loss: 0.0658
Epoch [39/50], Loss: 0.0599
Epoch [40/50], Loss: 0.0560
Epoch [41/50], Loss: 0.0533
Epoch [42/50], Loss: 0.0483
Epoch [43/50], Loss: 0.0508
Epoch [44/50], Loss: 0.0436
Epoch [45/50], Loss: 0.0523
Epoch [46/50], Loss: 0.0467
Epoch [47/50], Loss: 0.0487
Epoch [48/50], Loss: 0.0525
Epoch [49/50], Loss: 0.0492
Epoch [50/50], Loss: 0.0453

In [300]:
model.eval()

with torch.no_grad():
    test_loss = 0

    for batch_X, batch_y in test_loader:

        predictions = model(batch_X)

        loss = criterion(predictions, batch_y)

        test_loss += loss.item() * batch_X.size(0)

    test_loss /= len(test_loader.dataset)

    print(f"Test Loss: {test_loss:.4f}")

Test Loss: 0.5408

In [301]:
torch.save(model.state_dict(), "model/house_price_predictor.pth")

In [302]:
model

HousePricePredictor(
  (fc1): Linear(in_features=12, out_features=64, bias=True)
  (fc2): Linear(in_features=64, out_features=32, bias=True)
  (fc3): Linear(in_features=32, out_features=1, bias=True)
  (relu): ReLU()
)

In [303]:
prediction = target_scaler.inverse_transform(predictions.numpy())

In [304]:
prediction

array([[4.8367435e+06],
       [5.7363720e+06],
       [4.8095370e+06],
       [5.7266990e+06],
       [4.0358665e+06],
       [8.4160700e+06],
       [4.0257375e+06],
       [4.1802492e+06],
       [6.1246825e+06],
       [4.1754932e+06],
       [6.6331935e+06],
       [8.0350420e+06],
       [4.6302390e+06]], dtype=float32)